name: quartz
description: Desktop application for managing macOS VMs.

publish_to: none
homepage: https://softyes.com.br
repository: https://github.com/quartz-vmm/desktop
issue_tracker: https://github.com/quartz-vmm/desktop/issues

version: 0.1.0+1

environment:
  sdk: ^3.13.4
  flutter: ^3.47.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
